In [1]:
import pandas as pd

In [2]:
def filter_womens_world_cup(df):
    """
    Filters out rows from the DataFrame where the 'tournament_name' column contains "FIFA Women's World Cup".
    """
    return df[~df['tournament_name'].str.contains("FIFA Women's World Cup")]

## Award winners

In [28]:
award_winners = pd.read_csv("data/raw/award_winners.csv")

In [29]:
award_winners.head()

,key_id,tournament_id,tournament_name,award_id,award_name,shared,player_id,family_name,given_name,team_id,team_name,team_code
0,1,WC-1930,1930 FIFA Men's World Cup,A-4,Golden Boot,0,P-56486,Stábile,Guillermo,T-03,Argentina,ARG
1,2,WC-1930,1930 FIFA Men's World Cup,A-5,Silver Boot,0,P-18628,Cea,Pedro,T-84,Uruguay,URY
2,3,WC-1930,1930 FIFA Men's World Cup,A-6,Bronze Boot,0,P-71973,Patenaude,Bert,T-83,United States,USA
3,4,WC-1934,1934 FIFA Men's World Cup,A-4,Golden Boot,0,P-60513,Nejedlý,Oldřich,T-21,Czechoslovakia,CSK
4,5,WC-1934,1934 FIFA Men's World Cup,A-5,Silver Boot,1,P-77348,Conen,Edmund,T-31,Germany,DEU

In [ ]:
award_winners = filter_womens_world_cup(award_winners)

In [31]:
award_winners.head()

,key_id,tournament_id,tournament_name,award_id,award_name,shared,player_id,family_name,given_name,team_id,team_name,team_code
0,1,WC-1930,1930 FIFA Men's World Cup,A-4,Golden Boot,0,P-56486,Stábile,Guillermo,T-03,Argentina,ARG
1,2,WC-1930,1930 FIFA Men's World Cup,A-5,Silver Boot,0,P-18628,Cea,Pedro,T-84,Uruguay,URY
2,3,WC-1930,1930 FIFA Men's World Cup,A-6,Bronze Boot,0,P-71973,Patenaude,Bert,T-83,United States,USA
3,4,WC-1934,1934 FIFA Men's World Cup,A-4,Golden Boot,0,P-60513,Nejedlý,Oldřich,T-21,Czechoslovakia,CSK
4,5,WC-1934,1934 FIFA Men's World Cup,A-5,Silver Boot,1,P-77348,Conen,Edmund,T-31,Germany,DEU

In [32]:
award_winners.columns

Index(['key_id', 'tournament_id', 'tournament_name', 'award_id', 'award_name',
       'shared', 'player_id', 'family_name', 'given_name', 'team_id',
       'team_name', 'team_code'],
      dtype='str')

In [33]:
award_winners_proc = award_winners[['key_id', 'tournament_id', 'award_id', 'shared', 'player_id', 'team_id']]
award_winners_proc.rename(columns={'key_id': 'award_winner_id'}, inplace=True)
award_winners_proc

     award_winner_id tournament_id award_id  shared player_id team_id
0                  1       WC-1930      A-4       0   P-56486    T-03
1                  2       WC-1930      A-5       0   P-18628    T-84
2                  3       WC-1930      A-6       0   P-71973    T-83
3                  4       WC-1934      A-4       0   P-60513    T-21
4                  5       WC-1934      A-5       1   P-77348    T-31
..               ...           ...      ...     ...       ...     ...
195              196       WC-2022      A-4       0   P-64077    T-30
196              197       WC-2022      A-5       0   P-14758    T-03
197              198       WC-2022      A-6       0   P-89750    T-30
198              199       WC-2022      A-7       0   P-13162    T-03
199              200       WC-2022      A-8       0   P-10739    T-03

[141 rows x 6 columns]

In [34]:
award_winners_proc.to_csv("data/processed/award_winners.csv", index=False)

## Awards

In [35]:
awards = pd.read_csv("data/raw/awards.csv")

In [36]:
awards.head()

   key_id award_id   award_name       award_description  year_introduced
0       1      A-1  Golden Ball             best player             1978
1       2      A-2  Silver Ball      second best player             1978
2       3      A-3  Bronze Ball       third best player             1978
3       4      A-4  Golden Boot         top goal scorer             1930
4       5      A-5  Silver Boot  second top goal scorer             1930

In [37]:
awards.drop(columns=['key_id'], inplace=True)
awards.to_csv("data/processed/awards.csv", index=False)

## Bookings

In [20]:
bookings = pd.read_csv("data/raw/bookings.csv")
bookings.head()

,key_id,booking_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,...,given_name,shirt_number,minute_label,minute_regulation,minute_stoppage,match_period,yellow_card,red_card,second_yellow_card,sending_off
0,1,B-0001,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,Kakhi,11,30',30,0,first half,1,0,0,0
1,2,B-0002,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,Givi,19,31',31,0,first half,1,0,0,0
2,3,B-0003,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,Evgeny,6,34',34,0,first half,1,0,0,0
3,4,B-0004,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,...,Gustavo,3,60',60,0,second half,1,0,0,0
4,5,B-0005,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,Gennady,7,72',72,0,second half,1,0,0,0

In [ ]:
bookings = filter_womens_world_cup(bookings)

,key_id,booking_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,...,given_name,shirt_number,minute_label,minute_regulation,minute_stoppage,match_period,yellow_card,red_card,second_yellow_card,sending_off
0,1,B-0001,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,Kakhi,11,30',30,0,first half,1,0,0,0
1,2,B-0002,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,Givi,19,31',31,0,first half,1,0,0,0
2,3,B-0003,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,Evgeny,6,34',34,0,first half,1,0,0,0
3,4,B-0004,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,...,Gustavo,3,60',60,0,second half,1,0,0,0
4,5,B-0005,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,Gennady,7,72',72,0,second half,1,0,0,0

In [40]:
bookings.columns

Index(['key_id', 'booking_id', 'tournament_id', 'tournament_name', 'match_id',
       'match_name', 'match_date', 'stage_name', 'group_name', 'team_id',
       'team_name', 'team_code', 'home_team', 'away_team', 'player_id',
       'family_name', 'given_name', 'shirt_number', 'minute_label',
       'minute_regulation', 'minute_stoppage', 'match_period', 'yellow_card',
       'red_card', 'second_yellow_card', 'sending_off'],
      dtype='str')

In [42]:
bookings[['booking_id', 'tournament_id', 'match_id', 'team_id', 'player_id', 'minute_label',
       'minute_regulation', 'minute_stoppage', 'match_period', 'yellow_card',
       'red_card', 'second_yellow_card', 'sending_off']].to_csv("data/processed/bookings.csv", index=False)

## confederations

In [3]:
confederations = pd.read_csv("data/raw/confederations.csv")
confederations.head()

,key_id,confederation_id,confederation_name,confederation_code,confederation_wikipedia_link
0,1,CF-1,Asian Football Confederation,AFC,https://en.wikipedia.org/wiki/Asian_Football_C...
1,2,CF-2,Confederation of African Football,CAF,https://en.wikipedia.org/wiki/Confederation_of...
2,3,CF-3,"Confederation of North, Central American and C...",CONCACAF,https://en.wikipedia.org/wiki/CONCACAF
3,4,CF-4,South American Football Confederation,CONMEBOL,https://en.wikipedia.org/wiki/CONMEBOL
4,5,CF-5,Oceania Football Confederation,OFC,https://en.wikipedia.org/wiki/Oceania_Football...

In [4]:
confederations.drop(columns=['key_id', 'confederation_wikipedia_link'], inplace=True)
confederations.to_csv("data/processed/confederations.csv", index=False)

## Goals

In [5]:
goals = pd.read_csv("data/raw/goals.csv")
goals.head()

,key_id,goal_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,...,shirt_number,player_team_id,player_team_name,player_team_code,minute_label,minute_regulation,minute_stoppage,match_period,own_goal,penalty
0,1,G-0001,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,...,0,T-30,France,FRA,19',19,0,first half,0,0
1,2,G-0002,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,...,0,T-30,France,FRA,40',40,0,first half,0,0
2,3,G-0003,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,...,0,T-30,France,FRA,43',43,0,first half,0,0
3,4,G-0004,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-46,...,0,T-46,Mexico,MEX,70',70,0,second half,0,0
4,5,G-0005,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,...,0,T-30,France,FRA,87',87,0,second half,0,0

In [6]:
goals.columns

Index(['key_id', 'goal_id', 'tournament_id', 'tournament_name', 'match_id',
       'match_name', 'match_date', 'stage_name', 'group_name', 'team_id',
       'team_name', 'team_code', 'home_team', 'away_team', 'player_id',
       'family_name', 'given_name', 'shirt_number', 'player_team_id',
       'player_team_name', 'player_team_code', 'minute_label',
       'minute_regulation', 'minute_stoppage', 'match_period', 'own_goal',
       'penalty'],
      dtype='str')

In [7]:
goals[['goal_id', 'tournament_id', 'match_id', 'team_id', 'player_id', 'minute_label',
       'minute_regulation', 'minute_stoppage', 'match_period', 'own_goal', 'penalty']].to_csv("data/processed/goals.csv", index=False)

## Groups

In [9]:
groups = pd.read_csv("data/raw/groups.csv")
groups.head()

,key_id,tournament_id,tournament_name,stage_number,stage_name,group_name,count_teams
0,1,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,4
1,2,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 2,3
2,3,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 3,3
3,4,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 4,3
4,5,WC-1950,1950 FIFA Men's World Cup,1,first round,Group 1,4

In [10]:
groups = filter_womens_world_cup(groups)
groups.rename(columns={'key_id': 'group_id'}, inplace=True)

## Group standings

In [8]:
group_standings = pd.read_csv("data/raw/group_standings.csv")
group_standings.head()

,key_id,tournament_id,tournament_name,stage_number,stage_name,group_name,position,team_id,team_name,team_code,played,wins,draws,losses,goals_for,goals_against,goal_difference,points,advanced
0,1,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,1,T-03,Argentina,ARG,3,3,0,0,10,4,6,6,1
1,2,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,2,T-13,Chile,CHL,3,2,0,1,5,3,2,4,0
2,3,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,3,T-30,France,FRA,3,1,0,2,4,3,1,2,0
3,4,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 1,4,T-46,Mexico,MEX,3,0,0,3,4,13,-9,0,0
4,5,WC-1930,1930 FIFA Men's World Cup,1,group stage,Group 2,1,T-87,Yugoslavia,YUG,2,2,0,0,6,1,5,4,1

In [11]:
group_standings = filter_womens_world_cup(group_standings)
group_standings.rename(columns={'key_id': 'group_standing_id'}, inplace=True)

In [14]:
group_standings_with_group_ids = group_standings.merge(groups, how='left', left_on=['tournament_id', 'group_name', 'stage_name'], right_on=['tournament_id', 'group_name', 'stage_name'], suffixes=('_standing', '_group'))

In [16]:
group_standings_with_group_ids.columns

Index(['group_standing_id', 'tournament_id', 'tournament_name_standing',
       'stage_number_standing', 'stage_name', 'group_name', 'position',
       'team_id', 'team_name', 'team_code', 'played', 'wins', 'draws',
       'losses', 'goals_for', 'goals_against', 'goal_difference', 'points',
       'advanced', 'group_id', 'tournament_name_group', 'stage_number_group',
       'count_teams'],
      dtype='str')

In [19]:
groups.to_csv("data/processed/groups.csv", index=False)
group_standings_with_group_ids[['group_standing_id', 'group_id', 'position',
       'team_id', 'played', 'wins', 'draws', 'losses', 'goals_for',
       'goals_against', 'goal_difference', 'points', 'advanced']].to_csv("data/processed/group_standings.csv", index=False)

## Host Countries

In [20]:
host_countries = pd.read_csv("data/raw/host_countries.csv")
host_countries.head()

,key_id,tournament_id,tournament_name,team_id,team_name,team_code,performance
0,1,WC-1930,1930 FIFA Men's World Cup,T-84,Uruguay,URY,champions
1,2,WC-1934,1934 FIFA Men's World Cup,T-41,Italy,ITA,champions
2,3,WC-1938,1938 FIFA Men's World Cup,T-30,France,FRA,quater-finals
3,4,WC-1950,1950 FIFA Men's World Cup,T-09,Brazil,BRA,runners-up
4,5,WC-1954,1954 FIFA Men's World Cup,T-75,Switzerland,CHE,quarter-final

In [21]:
host_countries.rename(columns={'key_id': 'host_country_id'}, inplace=True)
host_countries = filter_womens_world_cup(host_countries)
host_countries.drop(columns=['team_name', 'team_code'], inplace=True)
host_countries.to_csv("data/processed/host_countries.csv", index=False)

## Managers

In [22]:
managers = pd.read_csv("data/raw/managers.csv")
managers.head()

,key_id,manager_id,family_name,given_name,female,country_name,manager_wikipedia_link
0,1,M-001,Acosta,Nelson,0,Uruguay,https://en.wikipedia.org/wiki/Nelson_Acosta
1,2,M-002,Addo,Otto,0,Ghana,https://en.wikipedia.org/wiki/Otto_Addo
2,3,M-003,Adshead,John,0,England,https://en.wikipedia.org/wiki/John_Adshead
3,4,M-004,Advocaat,Dick,0,Netherlands,https://en.wikipedia.org/wiki/Dick_Advocaat
4,5,M-005,Afranie,Emmanual Kwasi,0,Ghana,https://en.wikipedia.org/wiki/Emmanuel_Kwasi_A...

In [23]:
managers.drop(columns=['key_id', 'manager_wikipedia_link'], inplace=True)
managers.to_csv("data/processed/managers.csv", index=False)

## Manager appearances

In [24]:
manager_appearances = pd.read_csv("data/raw/manager_appearances.csv")
manager_appearances.head()

,key_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,team_code,home_team,away_team,manager_id,family_name,given_name,country_name
0,1,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,France,FRA,1,0,M-075,Caudron,Raoul,France
1,2,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-46,Mexico,MEX,0,1,M-235,Luque de Serrallonga,Juan,Mexico
2,3,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,1930-07-13,group stage,Group 4,T-83,United States,USA,1,0,M-265,Millar,Robert,Scotland
3,4,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,1930-07-13,group stage,Group 4,T-06,Belgium,BEL,0,1,M-140,Goetinck,Hector,Belgium
4,5,WC-1930,1930 FIFA Men's World Cup,M-1930-03,Yugoslavia vs Brazil,1930-07-14,group stage,Group 2,T-87,Yugoslavia,YUG,1,0,M-397,Simonović,Boško,Yugoslavia

In [26]:
manager_appearances.columns

Index(['key_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name',
       'match_date', 'stage_name', 'group_name', 'team_id', 'team_name',
       'team_code', 'home_team', 'away_team', 'manager_id', 'family_name',
       'given_name', 'country_name'],
      dtype='str')

In [28]:
manager_appearances = filter_womens_world_cup(manager_appearances)

In [29]:
manager_appearances[['key_id', 'match_id', 'team_id', 'manager_id']].to_csv("data/processed/manager_appearances.csv", index=False)

## Manager appointments

In [31]:
manager_appointments = pd.read_csv("data/raw/manager_appointments.csv")
manager_appointments.head()

,key_id,tournament_id,tournament_name,team_id,team_name,team_code,manager_id,family_name,given_name,country_name
0,1,WC-1930,1930 FIFA Men's World Cup,T-56,Peru,PER,M-061,Bru,Francisco,Spain
1,2,WC-1930,1930 FIFA Men's World Cup,T-30,France,FRA,M-075,Caudron,Raoul,France
2,3,WC-1930,1930 FIFA Men's World Cup,T-09,Brazil,BRA,M-091,de Carvalho Rodrigues,Píndaro,Brazil
3,4,WC-1930,1930 FIFA Men's World Cup,T-55,Paraguay,PRY,M-109,Durand Laguna,José,Argentina
4,5,WC-1930,1930 FIFA Men's World Cup,T-06,Belgium,BEL,M-140,Goetinck,Hector,Belgium

In [32]:
manager_appointments.rename(columns={'key_id': 'manager_appointment_id'}, inplace=True)
manager_appointments = filter_womens_world_cup(manager_appointments)
manager_appointments.columns

Index(['manager_appointment_id', 'tournament_id', 'tournament_name', 'team_id',
       'team_name', 'team_code', 'manager_id', 'family_name', 'given_name',
       'country_name'],
      dtype='str')

In [33]:
manager_appointments[['manager_appointment_id', 'tournament_id', 'team_id', 'manager_id']].to_csv("data/processed/manager_appointments.csv", index=False)

## Matches

In [34]:
matches = pd.read_csv("data/raw/matches.csv")
matches.head()

,key_id,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,...,away_team_score_margin,extra_time,penalty_shootout,score_penalties,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw
0,1,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
1,2,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,group stage,Group 4,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
2,3,WC-1930,1930 FIFA Men's World Cup,M-1930-03,Yugoslavia vs Brazil,group stage,Group 2,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0
3,4,WC-1930,1930 FIFA Men's World Cup,M-1930-04,Romania vs Peru,group stage,Group 3,1,0,0,...,-2,0,0,0-0,0,0,home team win,1,0,0
4,5,WC-1930,1930 FIFA Men's World Cup,M-1930-05,Argentina vs France,group stage,Group 1,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0

In [49]:
matches = filter_womens_world_cup(matches)

In [50]:
matches_with_group_ids = matches.merge(groups, how='left', left_on=['tournament_id', 'group_name', 'stage_name'], right_on=['tournament_id', 'group_name', 'stage_name'], suffixes=('_match', '_group'))
matches_with_group_ids.head()

,key_id,tournament_id,tournament_name_match,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,...,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw,group_id,tournament_name_group,stage_number,count_teams
0,1,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,...,0,0,home team win,1,0,0,1.0,1930 FIFA Men's World Cup,1.0,4.0
1,2,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,group stage,Group 4,1,0,0,...,0,0,home team win,1,0,0,4.0,1930 FIFA Men's World Cup,1.0,3.0
2,3,WC-1930,1930 FIFA Men's World Cup,M-1930-03,Yugoslavia vs Brazil,group stage,Group 2,1,0,0,...,0,0,home team win,1,0,0,2.0,1930 FIFA Men's World Cup,1.0,3.0
3,4,WC-1930,1930 FIFA Men's World Cup,M-1930-04,Romania vs Peru,group stage,Group 3,1,0,0,...,0,0,home team win,1,0,0,3.0,1930 FIFA Men's World Cup,1.0,3.0
4,5,WC-1930,1930 FIFA Men's World Cup,M-1930-05,Argentina vs France,group stage,Group 1,1,0,0,...,0,0,home team win,1,0,0,1.0,1930 FIFA Men's World Cup,1.0,4.0

In [51]:
matches_with_group_ids.group_id

0      1.0
1      4.0
2      2.0
3      3.0
4      1.0
      ...
959    NaN
960    NaN
961    NaN
962    NaN
963    NaN
Name: group_id, Length: 964, dtype: float64

In [52]:
matches_with_group_ids.columns

Index(['key_id', 'tournament_id', 'tournament_name_match', 'match_id',
       'match_name', 'stage_name', 'group_name', 'group_stage',
       'knockout_stage', 'replayed', 'replay', 'match_date', 'match_time',
       'stadium_id', 'stadium_name', 'city_name', 'country_name',
       'home_team_id', 'home_team_name', 'home_team_code', 'away_team_id',
       'away_team_name', 'away_team_code', 'score', 'home_team_score',
       'away_team_score', 'home_team_score_margin', 'away_team_score_margin',
       'extra_time', 'penalty_shootout', 'score_penalties',
       'home_team_score_penalties', 'away_team_score_penalties', 'result',
       'home_team_win', 'away_team_win', 'draw', 'group_id',
       'tournament_name_group', 'stage_number', 'count_teams'],
      dtype='str')

In [53]:
matches_with_group_ids[[ 'match_id','tournament_id', 'group_id',
       'match_name', 'stage_name', 'replay', 'match_date', 'match_time',
       'stadium_id', 'home_team_id', 'away_team_id', 'home_team_score',
       'away_team_score', 'extra_time', 'penalty_shootout',
       'home_team_score_penalties', 'away_team_score_penalties']].to_csv("data/processed/matches.csv", index=False)

## Penalty Kicks

In [54]:
penalties = pd.read_csv("data/raw/penalty_kicks.csv")
penalties.head()

,key_id,penalty_kick_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,team_code,home_team,away_team,player_id,family_name,given_name,shirt_number,converted
0,1,PK-001,WC-1982,1982 FIFA Men's World Cup,M-1982-50,West Germany vs France,1982-07-08,semi-finals,not applicable,T-86,West Germany,DEU,1,0,P-68969,Kaltz,Manfred,20,1
1,2,PK-002,WC-1982,1982 FIFA Men's World Cup,M-1982-50,West Germany vs France,1982-07-08,semi-finals,not applicable,T-86,West Germany,DEU,1,0,P-48686,Breitner,Paul,3,1
2,3,PK-003,WC-1982,1982 FIFA Men's World Cup,M-1982-50,West Germany vs France,1982-07-08,semi-finals,not applicable,T-86,West Germany,DEU,1,0,P-45695,Stielike,Uli,15,0
3,4,PK-004,WC-1982,1982 FIFA Men's World Cup,M-1982-50,West Germany vs France,1982-07-08,semi-finals,not applicable,T-86,West Germany,DEU,1,0,P-89975,Littbarski,Pierre,7,1
4,5,PK-005,WC-1982,1982 FIFA Men's World Cup,M-1982-50,West Germany vs France,1982-07-08,semi-finals,not applicable,T-86,West Germany,DEU,1,0,P-59574,Rummenigge,Karl-Heinz,11,1

In [56]:
penalties = filter_womens_world_cup(penalties)

In [55]:
penalties.columns

Index(['key_id', 'penalty_kick_id', 'tournament_id', 'tournament_name',
       'match_id', 'match_name', 'match_date', 'stage_name', 'group_name',
       'team_id', 'team_name', 'team_code', 'home_team', 'away_team',
       'player_id', 'family_name', 'given_name', 'shirt_number', 'converted'],
      dtype='str')

In [58]:
penalties[['penalty_kick_id', 'match_id', 'team_id', 'player_id', 'converted']].to_csv("data/processed/penalty_kicks.csv", index=False)

## Players

In [59]:
players = pd.read_csv("data/raw/players.csv")
players.head()

,key_id,player_id,family_name,given_name,birth_date,female,goal_keeper,defender,midfielder,forward,count_tournaments,list_tournaments,player_wikipedia_link
0,1,P-35894,A'Court,Alan,1934-09-30,0,0,0,0,1,1,1958,https://en.wikipedia.org/wiki/Alan_A%27Court
1,2,P-29915,Aarønes,Ann Kristin,1973-01-19,1,0,0,1,1,2,"1995, 1999",https://en.wikipedia.org/wiki/Ann_Kristin_Aar%...
2,3,P-03484,Aaronson,Brenden,2000-10-22,0,0,0,0,1,1,2022,https://en.wikipedia.org/wiki/Brenden_Aaronson
3,4,P-04189,Abadzhiev,Stefan,1934-07-03,0,0,0,0,1,1,1966,https://en.wikipedia.org/wiki/Stefan_Abadzhiev
4,5,P-03523,Abalo,Jean-Paul,1975-06-26,0,0,1,0,0,1,2006,https://en.wikipedia.org/wiki/Jean-Paul_Abalo

In [62]:
players = players[players['female'] == 0].copy()

In [64]:
players.columns

Index(['key_id', 'player_id', 'family_name', 'given_name', 'birth_date',
       'female', 'goal_keeper', 'defender', 'midfielder', 'forward',
       'count_tournaments', 'list_tournaments', 'player_wikipedia_link'],
      dtype='str')

In [65]:
players.drop(columns=['key_id', 'player_wikipedia_link'], inplace=True)

In [66]:
players.to_csv("data/processed/players.csv", index=False)

## Player Appearances

In [89]:
player_appearances = pd.read_csv("data/raw/player_appearances.csv")
player_appearances.head()

,key_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,...,home_team,away_team,player_id,family_name,given_name,shirt_number,position_name,position_code,starter,substitute
0,1,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-66980,Calderón,Ignacio,1,goal keeper,GK,1,0
1,2,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-64553,Peña,Gustavo,3,defender,DF,1,0
2,3,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-42664,Pérez,Mario,5,defender,DF,1,0
3,4,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-69898,Hernández,Guillermo,6,midfielder,MF,1,0
4,5,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-56971,Salgado,Horacio López,10,forward,FW,1,0

In [90]:
player_appearances = filter_womens_world_cup(player_appearances)
player_appearances.rename(columns={'key_id': 'player_appearance_id'}, inplace=True)
player_appearances.columns

Index(['player_appearance_id', 'tournament_id', 'tournament_name', 'match_id',
       'match_name', 'match_date', 'stage_name', 'group_name', 'team_id',
       'team_name', 'team_code', 'home_team', 'away_team', 'player_id',
       'family_name', 'given_name', 'shirt_number', 'position_name',
       'position_code', 'starter', 'substitute'],
      dtype='str')

In [92]:
player_appearances[['player_appearance_id', 'match_id', 'team_id', 'player_id', 'starter', 'substitute']].to_csv("data/processed/player_appearances.csv", index=False)

## Qualified teams

In [76]:
qualified_teams = pd.read_csv("data/raw/qualified_teams.csv")
qualified_teams.head()

,key_id,tournament_id,tournament_name,team_id,team_name,team_code,count_matches,performance
0,1,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,5,final
1,2,WC-1930,1930 FIFA Men's World Cup,T-06,Belgium,BEL,2,group stage
2,3,WC-1930,1930 FIFA Men's World Cup,T-07,Bolivia,BOL,2,group stage
3,4,WC-1930,1930 FIFA Men's World Cup,T-09,Brazil,BRA,2,group stage
4,5,WC-1930,1930 FIFA Men's World Cup,T-13,Chile,CHL,3,group stage

In [77]:
qualified_teams.rename(columns={'key_id': 'qualified_team_id'}, inplace=True)
qualified_teams = filter_womens_world_cup(qualified_teams)

In [79]:
qualified_teams.drop(columns=['team_name', 'team_code', 'tournament_name'], inplace=True)
qualified_teams

     qualified_team_id tournament_id team_id  count_matches  performance
0                    1       WC-1930    T-03              5        final
1                    2       WC-1930    T-06              2  group stage
2                    3       WC-1930    T-07              2  group stage
3                    4       WC-1930    T-09              2  group stage
4                    5       WC-1930    T-13              3  group stage
..                 ...           ...     ...            ...          ...
620                621       WC-2022    T-75              4  round of 16
621                622       WC-2022    T-79              3  group stage
622                623       WC-2022    T-83              4  round of 16
623                624       WC-2022    T-84              3  group stage
624                625       WC-2022    T-85              3  group stage

[489 rows x 5 columns]

In [80]:
qualified_teams.to_csv("data/processed/qualified_teams.csv", index=False)

## Referees

In [82]:
referees = pd.read_csv("data/raw/referees.csv")
referees.head()

,key_id,referee_id,family_name,given_name,female,country_name,confederation_id,confederation_name,confederation_code,referee_wikipedia_link
0,1,R-001,Abdel-Fatah,Essam,0,Egypt,CF-2,Confederation of African Football,CAF,https://en.wikipedia.org/wiki/Essam_Abd_El_Fatah
1,2,R-002,Abidoye,Bola Elizabeth,1,Nigeria,CF-2,Confederation of African Football,CAF,not available
2,3,R-003,Adair,John,0,Northern Ireland,CF-6,Union of European Football Associations,UEFA,not available
3,4,R-004,Adámková,Jana,1,Czech Republic,CF-6,Union of European Football Associations,UEFA,https://en.wikipedia.org/wiki/Jana_Ad%C3%A1mko...
4,5,R-005,Agboyi,Xonam,1,Togo,CF-2,Confederation of African Football,CAF,not available

In [83]:
referees.columns

Index(['key_id', 'referee_id', 'family_name', 'given_name', 'female',
       'country_name', 'confederation_id', 'confederation_name',
       'confederation_code', 'referee_wikipedia_link'],
      dtype='str')

In [84]:
referees[['referee_id', 'family_name', 'given_name', 'female', 'country_name', 'confederation_id']].to_csv("data/processed/referees.csv", index=False)

## referee appearances

In [85]:
referee_appearances = pd.read_csv("data/raw/referee_appearances.csv")
referee_appearances.head()

,key_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,referee_id,family_name,given_name,country_name,confederation_id,confederation_name,confederation_code
0,1,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,R-251,Lombardi,Domingo,Uruguay,CF-4,South American Football Confederation,CONMEBOL
1,2,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,1930-07-13,group stage,Group 4,R-260,Macías,José,Argentina,CF-4,South American Football Confederation,CONMEBOL
2,3,WC-1930,1930 FIFA Men's World Cup,M-1930-03,Yugoslavia vs Brazil,1930-07-14,group stage,Group 2,R-430,Tejada,Aníbal,Uruguay,CF-4,South American Football Confederation,CONMEBOL
3,4,WC-1930,1930 FIFA Men's World Cup,M-1930-04,Romania vs Peru,1930-07-14,group stage,Group 3,R-472,Warnken,Alberto,Chile,CF-4,South American Football Confederation,CONMEBOL
4,5,WC-1930,1930 FIFA Men's World Cup,M-1930-05,Argentina vs France,1930-07-15,group stage,Group 1,R-116,de Almeida Rêgo,Gilberto,Brazil,CF-4,South American Football Confederation,CONMEBOL

In [ ]:
referee_appearances = filter_womens_world_cup(referee_appearances)
referee_appearances.rename(columns={'key_id': 'referee_appearance_id'}, inplace=True)
referee_appearances.columns

Index(['key_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name',
       'match_date', 'stage_name', 'group_name', 'referee_id', 'family_name',
       'given_name', 'country_name', 'confederation_id', 'confederation_name',
       'confederation_code'],
      dtype='str')

In [88]:
referee_appearances[['referee_appearance_id', 'match_id', 'referee_id']].to_csv("data/processed/referee_appearances.csv", index=False)

## Referee Appointment

In [93]:
referee_appointments = pd.read_csv("data/raw/referee_appointments.csv")
referee_appointments.head()

,key_id,tournament_id,tournament_name,referee_id,family_name,given_name,country_name,confederation_id,confederation_name,confederation_code
0,1,WC-1930,1930 FIFA Men's World Cup,R-039,Balvay,Thomas,France,CF-6,Union of European Football Associations,UEFA
1,2,WC-1930,1930 FIFA Men's World Cup,R-091,Christophe,Henri,Belgium,CF-6,Union of European Football Associations,UEFA
2,3,WC-1930,1930 FIFA Men's World Cup,R-116,de Almeida Rêgo,Gilberto,Brazil,CF-4,South American Football Confederation,CONMEBOL
3,4,WC-1930,1930 FIFA Men's World Cup,R-236,Langenus,John,Belgium,CF-6,Union of European Football Associations,UEFA
4,5,WC-1930,1930 FIFA Men's World Cup,R-251,Lombardi,Domingo,Uruguay,CF-4,South American Football Confederation,CONMEBOL

In [94]:
referee_appointments = filter_womens_world_cup(referee_appointments)
referee_appointments.rename(columns={'key_id': 'referee_appointment_id'}, inplace=True)
referee_appointments.columns

Index(['referee_appointment_id', 'tournament_id', 'tournament_name',
       'referee_id', 'family_name', 'given_name', 'country_name',
       'confederation_id', 'confederation_name', 'confederation_code'],
      dtype='str')

In [95]:
referee_appointments[['referee_appointment_id', 'tournament_id', 'referee_id']].to_csv("data/processed/referee_appointments.csv", index=False)

## Squads / Player Appointments

In [96]:
squads = pd.read_csv("data/raw/squads.csv")
squads.head()

,key_id,tournament_id,tournament_name,team_id,team_name,team_code,player_id,family_name,given_name,shirt_number,position_name,position_code
0,1,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,P-69244,Bossio,Ángel,0,goal keeper,GK
1,2,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,P-23160,Botasso,Juan,0,goal keeper,GK
2,3,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,P-99230,Cherro,Roberto,0,forward,FW
3,4,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,P-41921,Chividini,Alberto,0,defender,DF
4,5,WC-1930,1930 FIFA Men's World Cup,T-03,Argentina,ARG,P-22739,Della Torre,José,0,defender,DF

In [98]:
squads = filter_womens_world_cup(squads)
squads.rename(columns={'key_id': 'player_appointment_id'}, inplace=True)
squads.columns

Index(['player_appointment_id', 'tournament_id', 'tournament_name', 'team_id',
       'team_name', 'team_code', 'player_id', 'family_name', 'given_name',
       'shirt_number', 'position_name', 'position_code'],
      dtype='str')

In [99]:
squads[['player_appointment_id', 'tournament_id', 'team_id', 'player_id']].to_csv("data/processed/player_appointments.csv", index=False)

## Stadiums

In [100]:
stadiums = pd.read_csv("data/raw/stadiums.csv")
stadiums.head()

,key_id,stadium_id,stadium_name,city_name,country_name,stadium_capacity,stadium_wikipedia_link,city_wikipedia_link
0,1,S-001,Estadio José Amalfitani,Buenos Aires,Argentina,49000,https://en.wikipedia.org/wiki/José_Amalfitani_...,https://en.wikipedia.org/wiki/Buenos_Aires
1,2,S-002,Estadio Monumental,Buenos Aires,Argentina,75000,https://en.wikipedia.org/wiki/Estadio_Monument...,https://en.wikipedia.org/wiki/Buenos_Aires
2,3,S-003,Estadio Chateau Carreras,Córdoba,Argentina,47000,https://en.wikipedia.org/wiki/Estadio_Mario_Al...,"https://en.wikipedia.org/wiki/Córdoba,_Argentina"
3,4,S-004,Estadio José María Minella,Mar del Plata,Argentina,44000,https://en.wikipedia.org/wiki/Estadio_José_Mar...,https://en.wikipedia.org/wiki/Mar_del_Plata
4,5,S-005,Estadio Ciudad de Mendoza,Mendoza,Argentina,35000,https://en.wikipedia.org/wiki/Estadio_Malvinas...,"https://en.wikipedia.org/wiki/Mendoza,_Argentina"

In [101]:
stadiums.drop(columns=['key_id', 'stadium_wikipedia_link', 'city_wikipedia_link'], inplace=True)
stadiums.to_csv("data/processed/stadiums.csv", index=False)

## Substitutions

In [102]:
substitutions = pd.read_csv("data/raw/substitutions.csv")
substitutions.head()

,key_id,substitution_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,...,player_id,family_name,given_name,shirt_number,minute_label,minute_regulation,minute_stoppage,match_period,going_off,coming_on
0,1,S-0001,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,P-60181,Serebryanikov,Viktor,15,46',46,0,second half,1,0
1,2,S-0002,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,P-59828,Puzach,Anatoliy,20,46',46,0,second half,0,1
2,3,S-0003,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,P-43733,Nodia,Givi,19,66',66,0,second half,1,0
3,4,S-0004,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-72,...,P-98262,Khmelnitsky,Vitaly,21,66',66,0,second half,0,1
4,5,S-0005,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,...,P-32657,Velarde,Mario,18,67',67,0,second half,1,0

In [103]:
substitutions = filter_womens_world_cup(substitutions)
substitutions.columns

Index(['key_id', 'substitution_id', 'tournament_id', 'tournament_name',
       'match_id', 'match_name', 'match_date', 'stage_name', 'group_name',
       'team_id', 'team_name', 'team_code', 'home_team', 'away_team',
       'player_id', 'family_name', 'given_name', 'shirt_number',
       'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period',
       'going_off', 'coming_on'],
      dtype='str')

In [104]:
substitutions[['substitution_id', 'match_id', 'team_id', 'player_id',
       'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period', 'going_off', 'coming_on']].to_csv("data/processed/substitutions.csv", index=False)

## team_appearances

In [105]:
team_appearances = pd.read_csv("data/raw/team_appearances.csv")
team_appearances.head()

,key_id,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,...,goals_against,goal_differential,extra_time,penalty_shootout,penalties_for,penalties_against,result,win,lose,draw
0,1,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,...,1,3,0,0,0,0,win,1,0,0
1,2,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,...,4,-3,0,0,0,0,lose,0,1,0
2,3,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,group stage,Group 4,1,0,0,...,0,3,0,0,0,0,win,1,0,0
3,4,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,group stage,Group 4,1,0,0,...,3,-3,0,0,0,0,lose,0,1,0
4,5,WC-1930,1930 FIFA Men's World Cup,M-1930-03,Yugoslavia vs Brazil,group stage,Group 2,1,0,0,...,1,1,0,0,0,0,win,1,0,0

All that information is already available at the matches table

## Teams

In [106]:
teams = pd.read_csv("data/raw/teams.csv")
teams.head()

,key_id,team_id,team_name,team_code,mens_team,womens_team,federation_name,region_name,confederation_id,confederation_name,confederation_code,mens_team_wikipedia_link,womens_team_wikipedia_link,federation_wikipedia_link
0,1,T-01,Algeria,DZA,1,0,Algerian Football Federation,Africa,CF-2,Confederation of African Football,CAF,https://en.wikipedia.org/wiki/Algeria_national...,not applicable,https://en.wikipedia.org/wiki/Algerian_Footbal...
1,2,T-02,Angola,AGO,1,0,Angolan Football Federation,Africa,CF-2,Confederation of African Football,CAF,https://en.wikipedia.org/wiki/Angola_national_...,not applicable,https://en.wikipedia.org/wiki/Angolan_Football...
2,3,T-03,Argentina,ARG,1,1,Argentine Football Association,South America,CF-4,South American Football Confederation,CONMEBOL,https://en.wikipedia.org/wiki/Argentina_nation...,https://en.wikipedia.org/wiki/Argentina_women'...,https://en.wikipedia.org/wiki/Argentine_Footba...
3,4,T-04,Australia,AUS,1,1,Football Australia,Oceania,CF-1,Asian Football Confederation,AFC,https://en.wikipedia.org/wiki/Australia_men%27...,https://en.wikipedia.org/wiki/Australia_women'...,https://en.wikipedia.org/wiki/Football_Australia
4,5,T-05,Austria,AUT,1,0,Austrian Football Association,Europe,CF-6,Union of European Football Associations,UEFA,https://en.wikipedia.org/wiki/Austria_national...,not applicable,https://en.wikipedia.org/wiki/Austrian_Footbal...

In [107]:
teams.columns

Index(['key_id', 'team_id', 'team_name', 'team_code', 'mens_team',
       'womens_team', 'federation_name', 'region_name', 'confederation_id',
       'confederation_name', 'confederation_code', 'mens_team_wikipedia_link',
       'womens_team_wikipedia_link', 'federation_wikipedia_link'],
      dtype='str')

In [108]:
teams[['team_id', 'team_name', 'team_code', 'federation_name', 'region_name', 'confederation_id']].to_csv("data/processed/teams.csv", index=False)

## Tournament stages

In [109]:
tournament_stages = pd.read_csv("data/raw/tournament_stages.csv")
tournament_stages.head()

,key_id,tournament_id,tournament_name,stage_number,stage_name,group_stage,knockout_stage,unbalanced_groups,start_date,end_date,count_matches,count_teams,count_scheduled,count_replays,count_playoffs,count_walkovers
0,1,WC-1930,1930 FIFA Men's World Cup,1,group stage,1,0,1,1930-07-13,1930-07-22,15,13,15,0,0,0
1,2,WC-1930,1930 FIFA Men's World Cup,2,semi-finals,0,1,0,1930-07-26,1930-07-27,2,4,2,0,0,0
2,3,WC-1930,1930 FIFA Men's World Cup,3,final,0,1,0,1930-07-30,1930-07-30,1,2,1,0,0,0
3,4,WC-1934,1934 FIFA Men's World Cup,1,round of 16,0,1,0,1934-05-27,1934-05-27,8,16,8,0,0,0
4,5,WC-1934,1934 FIFA Men's World Cup,2,quarter-finals,0,1,0,1934-05-31,1934-06-01,5,8,4,1,0,0

All of this can be obtained joining the existing tables

## Tournament standings

In [110]:
tournament_standings = pd.read_csv("data/raw/tournament_standings.csv")
tournament_standings.head()

,key_id,tournament_id,tournament_name,position,team_id,team_name,team_code
0,1,WC-1930,1930 FIFA Men's World Cup,1,T-84,Uruguay,URY
1,2,WC-1930,1930 FIFA Men's World Cup,2,T-03,Argentina,ARG
2,3,WC-1930,1930 FIFA Men's World Cup,3,T-83,United States,USA
3,4,WC-1930,1930 FIFA Men's World Cup,4,T-87,Yugoslavia,YUG
4,5,WC-1934,1934 FIFA Men's World Cup,1,T-41,Italy,ITA

In [111]:
tournament_standings.rename(columns={'key_id': 'tournament_standing_id'}, inplace=True)
tournament_standings = filter_womens_world_cup(tournament_standings)
tournament_standings[['tournament_standing_id', 'tournament_id', 'team_id', 'position']].to_csv("data/processed/tournament_standings.csv", index=False)

## Tournaments

In [112]:
tournaments = pd.read_csv("data/raw/tournaments.csv")
tournaments.head()

,key_id,tournament_id,tournament_name,year,start_date,end_date,host_country,winner,host_won,count_teams,group_stage,second_group_stage,final_round,round_of_16,quarter_finals,semi_finals,third_place_match,final
0,1,WC-1930,1930 FIFA Men's World Cup,1930,1930-07-13,1930-07-30,Uruguay,Uruguay,1,13,1,0,0,0,0,1,0,1
1,2,WC-1934,1934 FIFA Men's World Cup,1934,1934-05-27,1934-06-10,Italy,Italy,1,16,0,0,0,1,1,1,1,1
2,3,WC-1938,1938 FIFA Men's World Cup,1938,1938-06-04,1938-06-19,France,Italy,0,15,0,0,0,1,1,1,1,1
3,4,WC-1950,1950 FIFA Men's World Cup,1950,1950-06-24,1950-07-16,Brazil,Uruguay,0,13,1,0,1,0,0,0,0,0
4,5,WC-1954,1954 FIFA Men's World Cup,1954,1954-06-16,1954-07-04,Switzerland,West Germany,0,16,1,0,0,0,1,1,1,1

In [113]:
tournaments = filter_womens_world_cup(tournaments)
tournaments.columns

Index(['key_id', 'tournament_id', 'tournament_name', 'year', 'start_date',
       'end_date', 'host_country', 'winner', 'host_won', 'count_teams',
       'group_stage', 'second_group_stage', 'final_round', 'round_of_16',
       'quarter_finals', 'semi_finals', 'third_place_match', 'final'],
      dtype='str')

In [114]:
tournaments.drop(columns=['key_id'], inplace=True)
tournaments.to_csv("data/processed/tournaments.csv", index=False)