In [37]:
import requests
import pandas as pd
import json
from io import StringIO
import numpy as np

In [26]:
PAGE_TITLE = "List_of_FIFA_World_Cup_official_match_balls"
API_URL = "https://en.wikipedia.org/w/api.php"

In [27]:
def get_page_html(title: str) -> str:
    """Pide a la MediaWiki API el HTML ya renderizado del artículo."""
    params = {
        "action": "parse",
        "page": title,
        "format": "json",
        "prop": "text",
    }
    resp = requests.get(API_URL, params=params, headers={
        "User-Agent": "WorldCupAnalyticsAgent/1.0 (portfolio project)"
    })
    resp.raise_for_status()
    data = resp.json()
    return data["parse"]["text"]["*"]


def extract_tables(html: str) -> list[pd.DataFrame]:
    """pandas.read_html parsea todas las <table> del HTML."""
    return pd.read_html(html)

In [28]:
html = get_page_html(PAGE_TITLE)

In [29]:
html

'<div class="mw-content-ltr mw-parser-output" lang="en" dir="ltr"><p class="mw-empty-elt">\n</p>\n<figure class="mw-default-size" typeof="mw:File/Thumb"><a href="/wiki/File:Giant_balls.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Giant_balls.jpg/250px-Giant_balls.jpg" decoding="async" width="250" height="167" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Giant_balls.jpg/500px-Giant_balls.jpg 2x" data-file-width="1690" data-file-height="1126" /></a><figcaption>Large inflatable replicas of Adidas World Cup balls in <a href="/wiki/Cape_Town" title="Cape Town">Cape Town</a>, 2009: from left to right, <a href="/wiki/Adidas_Telstar" title="Adidas Telstar">Telstar</a> (1970), <a href="/wiki/Telstar_Durlast" class="mw-redirect" title="Telstar Durlast">Telstar Durlast</a> (1974), <a href="/wiki/Adidas_Tango" title="Adidas Tango">Tango</a> (1978), <a href="/wiki/Tango_Espa%C3%B1a" class="mw-redirect" title="Tango España">Tango España</a> (1982), <a href="/wiki/Adidas_Azteca" title="Adidas Azteca">Azteca</a> (1986), <a href="/wiki/Etrusco_Unico" class="mw-redirect" title="Etrusco Unico">Etrusco Unico</a> (1990), <a href="/wiki/Adidas_Questra" title="Adidas Questra">Questra</a> (1994), <a href="/wiki/Adidas_Tricolore" title="Adidas Tricolore">Tricolore</a> (1998), <a href="/wiki/Fevernova" class="mw-redirect" title="Fevernova">Fevernova</a> (2002), <a href="/wiki/Teamgeist" class="mw-redirect" title="Teamgeist">Teamgeist</a> (2006).</figcaption></figure> \n<p>This is a list of the official <a href="/wiki/Ball_(association_football)" title="Ball (association football)">match balls</a> for the <a href="/wiki/FIFA_World_Cup" title="FIFA World Cup">FIFA World Cup</a> finals tournaments.\n</p><p>From the <a href="/wiki/1970_FIFA_World_Cup" title="1970 FIFA World Cup">1970 FIFA World Cup</a>, different official match balls have been used by <a href="/wiki/FIFA" title="FIFA">FIFA</a>.<sup id="cite&#95;ref-1" class="reference"><a href="#cite_note-1"><span class="cite-bracket">&#91;</span>1<span class="cite-bracket">&#93;</span></a></sup><sup id="cite&#95;ref-2" class="reference"><a href="#cite_note-2"><span class="cite-bracket">&#91;</span>2<span class="cite-bracket">&#93;</span></a></sup>\n</p>\n<meta property="mw:PageProp/toc" />\n<div class="mw-heading mw-heading2"><h2 id="List">List</h2><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=List_of_FIFA_World_Cup_official_match_balls&amp;action=edit&amp;section=1" title="Edit section: List"><span>edit</span></a><span class="mw-editsection-bracket">]</span></span></div>\n<table class="wikitable sortable">\n\n<tbody><tr>\n<th>Edition\n</th>\n<th colspan="2">Match ball\n</th>\n<th>Manufacturer\n</th>\n<th>Panels\n</th>\n<th>Additional information\n</th>\n<th><abbr title="Reference(s)">Ref.</abbr>\n</th></tr>\n<tr>\n<td align="center"><a href="/wiki/1930_FIFA_World_Cup" title="1930 FIFA World Cup">1930</a>\n</td>\n<th scope="row"><span class="nowrap">Tiento <span style="font-size: 85%;">(1st half)</span><br />T-Model <span style="font-size: 85%;">(2nd half)</span></span>\n</th>\n<td><div class="switcher-container"><div> <span typeof="mw:File"><a href="/wiki/File:1930_World_Cup_Final_ball_Argentina.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f2/1930_World_Cup_Final_ball_Argentina.jpg/120px-1930_World_Cup_Final_ball_Argentina.jpg" decoding="async" width="100" height="98" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f2/1930_World_Cup_Final_ball_Argentina.jpg/250px-1930_World_Cup_Final_ball_Argentina.jpg 2x" data-file-width="1207" data-file-height="1183" /></a></span>\n<span class="switcher-label" style="display:none">Tiento</span></div><div> <span typeof="mw:File"><a href="/wiki/File:1930_World_Cup_Final_Ball_Uruguay.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b7/1930_World_Cup_Final_Ball_Uruguay.jpg/120px-1930_World_Cup_Final_Ball_Uruguay.jpg" decoding="async" width="100" height="107" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b7/1930_World_Cup_Final_Ball_Uruguay.jpg/250px-1930_World_Cup_Final_Ball_Uruguay.jpg 2x" data-file-width="1193" data-file-height="1276" /></a></span> \n<span class="switcher-label" style="display:none">T-Model</span></div></div> \n</td>\n<td>—\n</td>\n<td>\n</td>\n<td>Two different balls were used in <a href="/wiki/1930_FIFA_World_Cup_Final" class="mw-redirect" title="1930 FIFA World Cup Final">the final</a>: Argentina supplied the first-half ball (the \'Tiento\') and led 2–1 at the break; hosts Uruguay supplied the second-half ball (the \'T-Model\' which was larger and heavier)<sup id="cite&#95;ref-blizzard6&#95;3-0" class="reference"><a href="#cite_note-blizzard6-3"><span class="cite-bracket">&#91;</span>3<span class="cite-bracket">&#93;</span></a></sup> and won 4–2.\n</td>\n<td><sup id="cite&#95;ref-blizzard6&#95;3-1" class="reference"><a href="#cite_note-blizzard6-3"><span class="cite-bracket">&#91;</span>3<span class="cite-bracket">&#93;</span></a></sup><sup id="cite&#95;ref-fifalist&#95;4-0" class="reference"><a href="#cite_note-fifalist-4"><span class="cite-bracket">&#91;</span>4<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1934_FIFA_World_Cup" title="1934 FIFA World Cup">1934</a>\n</td>\n<th scope="row">Federale 102\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Federale_102.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Federale_102.jpg/120px-Federale_102.jpg" decoding="async" width="100" height="100" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Federale_102.jpg/250px-Federale_102.jpg 2x" data-file-width="750" data-file-height="750" /></a></span>\n</td>\n<td>ECAS<br />(Ente Centrale Approvvigionamento Sportivi), Rome\n</td>\n<td>\n</td>\n<td>\n</td>\n<td><sup id="cite&#95;ref-5" class="reference"><a href="#cite_note-5"><span class="cite-bracket">&#91;</span>5<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1938_FIFA_World_Cup" title="1938 FIFA World Cup">1938</a>\n</td>\n<th scope="row">Allen\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Allen-1938.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/1/11/Allen-1938.jpg/120px-Allen-1938.jpg" decoding="async" width="100" height="100" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/11/Allen-1938.jpg/250px-Allen-1938.jpg 2x" data-file-width="305" data-file-height="305" /></a></span>\n</td>\n<td>Allen, Paris\n</td>\n<td>13\n</td>\n<td>Made up of leather, It had white cotton laces on a separate, thin panel.\n</td>\n<td><sup id="cite&#95;ref-6" class="reference"><a href="#cite_note-6"><span class="cite-bracket">&#91;</span>6<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1950_FIFA_World_Cup" title="1950 FIFA World Cup">1950</a>\n</td>\n<th scope="row">Duplo T\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Duplo_T-1950.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/9/93/Duplo_T-1950.jpg/120px-Duplo_T-1950.jpg" decoding="async" width="100" height="100" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/93/Duplo_T-1950.jpg/250px-Duplo_T-1950.jpg 2x" data-file-width="305" data-file-height="305" /></a></span>\n</td>\n<td>Superball\n</td>\n<td>12\n</td>\n<td>First ball to have no laces and introduce the syringe valve.\n</td>\n<td><sup id="cite&#95;ref-7" class="reference"><a href="#cite_note-7"><span class="cite-bracket">&#91;</span>7<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1954_FIFA_World_Cup" title="1954 FIFA World Cup">1954</a>\n</td>\n<th scope="row">Swiss World Champion\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Swiss_World_Champion-1954.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Swiss_World_Champion-1954.jpg/120px-Swiss_World_Champion-1954.jpg" decoding="async" width="100" height="100" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Swiss_World_Champion-1954.jpg/250px-Swiss_World_Champion-1954.jpg 2x" data-file-width="400" data-file-height="400" /></a></span>\n</td>\n<td>Kost Sport, Basel\n</td>\n<td>18\n</td>\n<td>The first 18-panel ball.\n</td>\n<td><sup id="cite&#95;ref-fifalist&#95;4-1" class="reference"><a href="#cite_note-fifalist-4"><span class="cite-bracket">&#91;</span>4<span class="cite-bracket">&#93;</span></a></sup><sup id="cite&#95;ref-8" class="reference"><a href="#cite_note-8"><span class="cite-bracket">&#91;</span>8<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1958_FIFA_World_Cup" title="1958 FIFA World Cup">1958</a>\n</td>\n<th scope="row">Top Star\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Top_Star-1958.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Top_Star-1958.jpg/120px-Top_Star-1958.jpg" decoding="async" width="100" height="100" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Top_Star-1958.jpg/250px-Top_Star-1958.jpg 2x" data-file-width="320" data-file-height="320" /></a></span>\n</td>\n<td>Sydsvenska Läder och Remfabriken, <a href="/wiki/%C3%84ngelholm" title="Ängelholm">Ängelholm</a><br />(aka "Remmen" or "Sydläder")\n</td>\n<td>\n</td>\n<td>Chosen from 102 candidates in a blind test by four FIFA officials.\n</td>\n<td><sup id="cite&#95;ref-Norlin&#95;9-0" class="reference"><a href="#cite_note-Norlin-9"><span class="cite-bracket">&#91;</span>9<span class="cite-bracket">&#93;</span></a></sup><sup id="cite&#95;ref-10" class="reference"><a href="#cite_note-10"><span class="cite-bracket">&#91;</span>10<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1962_FIFA_World_Cup" title="1962 FIFA World Cup">1962</a>\n</td>\n<th scope="row"><a href="/wiki/Crack_(ball)" title="Crack (ball)">Crack</a>\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Crack-1962.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Crack-1962.jpg/120px-Crack-1962.jpg" decoding="async" width="100" height="100" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Crack-1962.jpg/250px-Crack-1962.jpg 2x" data-file-width="510" data-file-height="510" /></a></span>\n</td>\n<td>Señor Custodio Zamora H.,<br /><a href="/wiki/San_Miguel,_Chile" title="San Miguel, Chile">San Miguel, Chile</a> Remmen\n</td>\n<td>18\n</td>\n<td>The Crack was the official ball. Referee <a href="/wiki/Ken_Aston" title="Ken Aston">Ken Aston</a> was unimpressed with the Chilean ball provided for the opening match, and sent for a European ball, which arrived in the second half. Various matches used different balls, with the apparent rumour the European teams did not trust the locally produced ball.<sup id="cite&#95;ref-blizzard6&#95;3-2" class="reference"><a href="#cite_note-blizzard6-3"><span class="cite-bracket">&#91;</span>3<span class="cite-bracket">&#93;</span></a></sup>\n</td>\n<td><sup id="cite&#95;ref-blizzard6&#95;3-3" class="reference"><a href="#cite_note-blizzard6-3"><span class="cite-bracket">&#91;</span>3<span class="cite-bracket">&#93;</span></a></sup><sup id="cite&#95;ref-fifalist&#95;4-2" class="reference"><a href="#cite_note-fifalist-4"><span class="cite-bracket">&#91;</span>4<span class="cite-bracket">&#93;</span></a></sup><sup id="cite&#95;ref-Norlin&#95;9-1" class="reference"><a href="#cite_note-Norlin-9"><span class="cite-bracket">&#91;</span>9<span class="cite-bracket">&#93;</span></a></sup><sup id="cite&#95;ref-crack1962&#95;11-0" class="reference"><a href="#cite_note-crack1962-11"><span class="cite-bracket">&#91;</span>11<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1966_FIFA_World_Cup" title="1966 FIFA World Cup">1966</a>\n</td>\n<th scope="row"><a href="/wiki/Slazenger_Challenge_4-Star" title="Slazenger Challenge 4-Star">Challenge 4-Star</a>\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Challenge_4-star-1966.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/1/19/Challenge_4-star-1966.jpg/120px-Challenge_4-star-1966.jpg" decoding="async" width="100" height="100" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/19/Challenge_4-star-1966.jpg/250px-Challenge_4-star-1966.jpg 2x" data-file-width="285" data-file-height="285" /></a></span>\n</td>\n<td><a href="/wiki/Slazenger" title="Slazenger">Slazenger</a>\n</td>\n<td>25\n</td>\n<td>In orange or yellow. Selected in a blind test at <a href="/wiki/The_Football_Association" title="The Football Association">the Football Association</a> headquarters in <a href="/wiki/Soho_Square" title="Soho Square">Soho Square</a>.\n</td>\n<td><sup id="cite&#95;ref-fifalist&#95;4-3" class="reference"><a href="#cite_note-fifalist-4"><span class="cite-bracket">&#91;</span>4<span class="cite-bracket">&#93;</span></a></sup><sup id="cite&#95;ref-12" class="reference"><a href="#cite_note-12"><span class="cite-bracket">&#91;</span>12<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1970_FIFA_World_Cup" title="1970 FIFA World Cup">1970</a>\n</td>\n<th scope="row"><a href="/wiki/Adidas_Telstar" title="Adidas Telstar">Telstar</a>\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Adidas_Telstar_Mexico_1970_Official_ball.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Adidas_Telstar_Mexico_1970_Official_ball.jpg/120px-Adidas_Telstar_Mexico_1970_Official_ball.jpg" decoding="async" width="100" height="67" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Adidas_Telstar_Mexico_1970_Official_ball.jpg/250px-Adidas_Telstar_Mexico_1970_Official_ball.jpg 2x" data-file-width="2592" data-file-height="1728" /></a></span>\n</td>\n<td rowspan="29"><a href="/wiki/Adidas" title="Adidas">Adidas</a>\n</td>\n<td rowspan="10">32 (20 hexagons and 12 pentagons)\n</td>\n<td>Telstar was the first 32-panel black-and-white ball used in the FIFA World Cup finals. Only 20 were supplied by Adidas. A brown ball (Germany-Peru) and a white ball (first half of Italy-Germany) were used in some matches.\n</td>\n<td><sup id="cite&#95;ref-fifalist&#95;4-4" class="reference"><a href="#cite_note-fifalist-4"><span class="cite-bracket">&#91;</span>4<span class="cite-bracket">&#93;</span></a></sup><sup id="cite&#95;ref-13" class="reference"><a href="#cite_note-13"><span class="cite-bracket">&#91;</span>13<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1974_FIFA_World_Cup" title="1974 FIFA World Cup">1974</a>\n</td>\n<th scope="row"><a href="/wiki/Adidas_Telstar_Durlast" class="mw-redirect" title="Adidas Telstar Durlast">Telstar Durlast</a>\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Fifaworldcup1974.JPG" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Fifaworldcup1974.JPG/120px-Fifaworldcup1974.JPG" decoding="async" width="100" height="139" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Fifaworldcup1974.JPG/250px-Fifaworldcup1974.JPG 2x" data-file-width="1419" data-file-height="1970" /></a></span>\n</td>\n<td>The first polyurethane coated ball, making it waterproof and resistant to wear and tear.\n</td>\n<td><sup id="cite&#95;ref-fifalist&#95;4-5" class="reference"><a href="#cite_note-fifalist-4"><span class="cite-bracket">&#91;</span>4<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1978_FIFA_World_Cup" title="1978 FIFA World Cup">1978</a>\n</td>\n<th scope="row"><a href="/wiki/Adidas_Tango" title="Adidas Tango">Tango</a>\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Adidas_Tango_Argentina_(River_Plate)_1978_cup_Official_ball.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Adidas_Tango_Argentina_%28River_Plate%29_1978_cup_Official_ball.jpg/120px-Adidas_Tango_Argentina_%28River_Plate%29_1978_cup_Official_ball.jpg" decoding="async" width="100" height="67" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Adidas_Tango_Argentina_%28River_Plate%29_1978_cup_Official_ball.jpg/250px-Adidas_Tango_Argentina_%28River_Plate%29_1978_cup_Official_ball.jpg 2x" data-file-width="2592" data-file-height="1728" /></a></span>\n</td>\n<td>The first of a family of footballs that was also used in the UEFA European Championships and the Summer Olympics until 1988.\n</td>\n<td><sup id="cite&#95;ref-fifalist&#95;4-6" class="reference"><a href="#cite_note-fifalist-4"><span class="cite-bracket">&#91;</span>4<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1982_FIFA_World_Cup" title="1982 FIFA World Cup">1982</a>\n</td>\n<th scope="row"><a href="/wiki/Adidas_Tango_Espa%C3%B1a" class="mw-redirect" title="Adidas Tango España">Tango España</a>\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Adidas_Tango_Espa%C3%B1a.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Adidas_Tango_Espa%C3%B1a.jpg/120px-Adidas_Tango_Espa%C3%B1a.jpg" decoding="async" width="100" height="150" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Adidas_Tango_Espa%C3%B1a.jpg/250px-Adidas_Tango_Espa%C3%B1a.jpg 2x" data-file-width="1126" data-file-height="1690" /></a></span>\n</td>\n<td>Similar to its predecessor the Tango the Tango España had a polyurethane coating. It had new and improved rubberized seams and was the last leather ball to be used in the World Cup.\n</td>\n<td><sup id="cite&#95;ref-fifalist&#95;4-7" class="reference"><a href="#cite_note-fifalist-4"><span class="cite-bracket">&#91;</span>4<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1986_FIFA_World_Cup" title="1986 FIFA World Cup">1986</a>\n</td>\n<th scope="row"><a href="/wiki/Adidas_Azteca" title="Adidas Azteca">Azteca</a>\n</th>\n<td><span typeof="mw:File"><a href="/wiki/File:Adidas_Azteca_Mexico_1986_Official_ball.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/0/08/Adidas_Azteca_Mexico_1986_Official_ball.jpg/120px-Adidas_Azteca_Mexico_1986_Official_ball.jpg" decoding="async" width="100" height="67" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/08/Adidas_Azteca_Mexico_1986_Official_ball.jpg/250px-Adidas_Azteca_Mexico_1986_Official_ball.jpg 2x" data-file-width="2592" data-file-height="1728" /></a></span>\n</td>\n<td>First fully synthetic FIFA World Cup ball and first hand-sewed ball. The decoration consisted of triangles inspired by Aztec art, making it the first ball to have clear references to the host country in its design. The name comes from the pre-Columbian civilization that existed in Mexico when the Spanish arrived in the 16th century.\n</td>\n<td><sup id="cite&#95;ref-fifalist&#95;4-8" class="reference"><a href="#cite_note-fifalist-4"><span class="cite-bracket">&#91;</span>4<span class="cite-bracket">&#93;</span></a></sup>\n</td></tr>\n<tr>\n<td align="center"><a href="/wiki/1990_FIFA_World_Cup" title="1990 FIFA World Cup">1990</a>\n</td>\n<th scope="row"><a href="/wiki/Adidas_Etrusco_Unico" title="Adidas Etrusco Unico">Etrusco Unico</a>\n</th>\n<td><span typeof="mw:Fi

In [30]:
tables = pd.read_html(StringIO(html))

In [31]:
tables[0]

,Edition,Match ball,Match ball.1,Manufacturer,Panels,Additional information,Ref.
0,1930,Tiento (1st half) T-Model (2nd half),NaN,—,NaN,Two different balls were used in the final: Ar...,[3][4]
1,1934,Federale 102,NaN,ECAS (Ente Centrale Approvvigionamento Sportiv...,NaN,NaN,[5]
2,1938,Allen,NaN,"Allen, Paris",13,"Made up of leather, It had white cotton laces ...",[6]
3,1950,Duplo T,NaN,Superball,12,First ball to have no laces and introduce the ...,[7]
4,1954,Swiss World Champion,NaN,"Kost Sport, Basel",18,The first 18-panel ball.,[4][8]
5,1958,Top Star,NaN,"Sydsvenska Läder och Remfabriken, Ängelholm (a...",NaN,Chosen from 102 candidates in a blind test by ...,[9][10]
6,1962,Crack,NaN,"Señor Custodio Zamora H., San Miguel, Chile Re...",18,The Crack was the official ball. Referee Ken A...,[3][4][9][11]
7,1966,Challenge 4-Star,NaN,Slazenger,25,In orange or yellow. Selected in a blind test ...,[4][12]
8,1970,Telstar,NaN,Adidas,32 (20 hexagons and 12 pentagons),Telstar was the first 32-panel black-and-white...,[4][13]
9,1974,Telstar Durlast,NaN,Adidas,32 (20 hexagons and 12 pentagons),"The first polyurethane coated ball, making it ...",[4]
10,1978,Tango,NaN,Adidas,32 (20 hexagons and 12 pentagons),The first of a family of footballs that was al...,[4]
11,1982,Tango España,NaN,Adidas,32 (20 hexagons and 12 pentagons),Similar to its predecessor the Tango the Tango...,[4]
12,1986,Azteca,NaN,Adidas,32 (20 hexagons and 12 pentagons),First fully synthetic FIFA World Cup ball and ...,[4]
13,1990,Etrusco Unico,NaN,Adidas,32 (20 hexagons and 12 pentagons),The design was also inspired by the 1978 Tango...,[4]
14,1994,Questra[14],NaN,Adidas,32 (20 hexagons and 12 pentagons),The name derives from an Old English phrase me...,[4]
15,1998,Tricolore,NaN,Adidas,32 (20 hexagons and 12 pentagons),First multi-coloured ball at a World Cup final...,[4]
16,1999 (women),Icon,NaN,Adidas,32 (20 hexagons and 12 pentagons),First ball specifically created for a Women's ...,[15][16]
17,2002,Fevernova,NaN,Adidas,32 (20 hexagons and 12 pentagons),First World Cup ball with a triangular design....,[4]
18,2006,Teamgeist,NaN,Adidas,14,Each match at the World Cup finals had its own...,[4]
19,2006,Teamgeist Berlin,NaN,Adidas,14,Each match at the World Cup finals had its own...,[4]
20,2010,Jabulani,NaN,Adidas,8,A special variant was used for the final match...,[4][20]
21,2010,Jo'bulani,NaN,Adidas,8,A special variant was used for the final match...,[4][20]
22,2011 (women),SpeedCell,NaN,Adidas,8,"Technically identical to the Jabulani, but wit...",[21]
23,2014,Brazuca,NaN,Adidas,6,This is the first FIFA World Cup ball named by...,[22]
24,2014,Brazuca Final Rio,NaN,Adidas,6,This is the first FIFA World Cup ball named by...,[22]
25,2015 (women),Conext 15,NaN,Adidas,6,Based on the technology introduced in the Braz...,[23]
26,2015 (women),Conext 15 Final Vancouver,NaN,Adidas,6,Based on the technology introduced in the Braz...,[23]
27,2018,Telstar 18,NaN,Adidas,6,"For the 48 matches in the Group stage, teams c...",[25]
28,2018,Telstar Mechta,NaN,Adidas,6,"At the end of the 2018 World Cup group stage, ...",[26]
29,2019 (women),Conext 19,NaN,Adidas,6,Used for 36 matches in the group stage. It sha...,[28]
30,2019 (women),Tricolore 19,NaN,Adidas,6,Inspired by the Tricolore ball and based on th...,[28]
31,2022,Al Rihla,NaN,Adidas,20,The ball was designed with sustainability as a...,NaN
32,2022,Al Hilm,NaN,Adidas,20,The ball was designed with sustainability as a...,NaN
33,2023 (women),Oceaunz,NaN,Adidas,20,The official match ball used during the early ...,[30]
34,2023 (women),Oceaunz Final Pro,NaN,Adidas,20,The official match ball used during the early ...,[31]
35,2026,Trionda,NaN,Adidas,4,"Trionda is from the combination of the words ""...",[32]
36,2026,Trionda Final,NaN,Adidas,4,"Trionda is from the combination of the words ""...",[33][34]

In [32]:
match_balls_df = tables[0].copy()
match_balls_df = match_balls_df[~match_balls_df['Edition'].str.contains('women')].reset_index(drop=True).copy()
match_balls_df

,Edition,Match ball,Match ball.1,Manufacturer,Panels,Additional information,Ref.
0,1930,Tiento (1st half) T-Model (2nd half),NaN,—,NaN,Two different balls were used in the final: Ar...,[3][4]
1,1934,Federale 102,NaN,ECAS (Ente Centrale Approvvigionamento Sportiv...,NaN,NaN,[5]
2,1938,Allen,NaN,"Allen, Paris",13,"Made up of leather, It had white cotton laces ...",[6]
3,1950,Duplo T,NaN,Superball,12,First ball to have no laces and introduce the ...,[7]
4,1954,Swiss World Champion,NaN,"Kost Sport, Basel",18,The first 18-panel ball.,[4][8]
5,1958,Top Star,NaN,"Sydsvenska Läder och Remfabriken, Ängelholm (a...",NaN,Chosen from 102 candidates in a blind test by ...,[9][10]
6,1962,Crack,NaN,"Señor Custodio Zamora H., San Miguel, Chile Re...",18,The Crack was the official ball. Referee Ken A...,[3][4][9][11]
7,1966,Challenge 4-Star,NaN,Slazenger,25,In orange or yellow. Selected in a blind test ...,[4][12]
8,1970,Telstar,NaN,Adidas,32 (20 hexagons and 12 pentagons),Telstar was the first 32-panel black-and-white...,[4][13]
9,1974,Telstar Durlast,NaN,Adidas,32 (20 hexagons and 12 pentagons),"The first polyurethane coated ball, making it ...",[4]
10,1978,Tango,NaN,Adidas,32 (20 hexagons and 12 pentagons),The first of a family of footballs that was al...,[4]
11,1982,Tango España,NaN,Adidas,32 (20 hexagons and 12 pentagons),Similar to its predecessor the Tango the Tango...,[4]
12,1986,Azteca,NaN,Adidas,32 (20 hexagons and 12 pentagons),First fully synthetic FIFA World Cup ball and ...,[4]
13,1990,Etrusco Unico,NaN,Adidas,32 (20 hexagons and 12 pentagons),The design was also inspired by the 1978 Tango...,[4]
14,1994,Questra[14],NaN,Adidas,32 (20 hexagons and 12 pentagons),The name derives from an Old English phrase me...,[4]
15,1998,Tricolore,NaN,Adidas,32 (20 hexagons and 12 pentagons),First multi-coloured ball at a World Cup final...,[4]
16,2002,Fevernova,NaN,Adidas,32 (20 hexagons and 12 pentagons),First World Cup ball with a triangular design....,[4]
17,2006,Teamgeist,NaN,Adidas,14,Each match at the World Cup finals had its own...,[4]
18,2006,Teamgeist Berlin,NaN,Adidas,14,Each match at the World Cup finals had its own...,[4]
19,2010,Jabulani,NaN,Adidas,8,A special variant was used for the final match...,[4][20]
20,2010,Jo'bulani,NaN,Adidas,8,A special variant was used for the final match...,[4][20]
21,2014,Brazuca,NaN,Adidas,6,This is the first FIFA World Cup ball named by...,[22]
22,2014,Brazuca Final Rio,NaN,Adidas,6,This is the first FIFA World Cup ball named by...,[22]
23,2018,Telstar 18,NaN,Adidas,6,"For the 48 matches in the Group stage, teams c...",[25]
24,2018,Telstar Mechta,NaN,Adidas,6,"At the end of the 2018 World Cup group stage, ...",[26]
25,2022,Al Rihla,NaN,Adidas,20,The ball was designed with sustainability as a...,NaN
26,2022,Al Hilm,NaN,Adidas,20,The ball was designed with sustainability as a...,NaN
27,2026,Trionda,NaN,Adidas,4,"Trionda is from the combination of the words ""...",[32]
28,2026,Trionda Final,NaN,Adidas,4,"Trionda is from the combination of the words ""...",[33][34]

In [33]:
match_balls_df.rename(columns={
    'Edition': 'tournament_id',
    'Match ball': 'ball_name',
    'Manufacturer': 'manufacturer'}, inplace=True)

match_balls_df['tournament_id'] = 'WC-' + match_balls_df['tournament_id']
match_balls_df.drop(columns=['Match ball.1', 'Panels',	'Additional information', 'Ref.'], inplace=True)
match_balls_df

,tournament_id,ball_name,manufacturer
0,WC-1930,Tiento (1st half) T-Model (2nd half),—
1,WC-1934,Federale 102,ECAS (Ente Centrale Approvvigionamento Sportiv...
2,WC-1938,Allen,"Allen, Paris"
3,WC-1950,Duplo T,Superball
4,WC-1954,Swiss World Champion,"Kost Sport, Basel"
5,WC-1958,Top Star,"Sydsvenska Läder och Remfabriken, Ängelholm (a..."
6,WC-1962,Crack,"Señor Custodio Zamora H., San Miguel, Chile Re..."
7,WC-1966,Challenge 4-Star,Slazenger
8,WC-1970,Telstar,Adidas
9,WC-1974,Telstar Durlast,Adidas
10,WC-1978,Tango,Adidas
11,WC-1982,Tango España,Adidas
12,WC-1986,Azteca,Adidas
13,WC-1990,Etrusco Unico,Adidas
14,WC-1994,Questra[14],Adidas
15,WC-1998,Tricolore,Adidas
16,WC-2002,Fevernova,Adidas
17,WC-2006,Teamgeist,Adidas
18,WC-2006,Teamgeist Berlin,Adidas
19,WC-2010,Jabulani,Adidas
20,WC-2010,Jo'bulani,Adidas
21,WC-2014,Brazuca,Adidas
22,WC-2014,Brazuca Final Rio,Adidas
23,WC-2018,Telstar 18,Adidas
24,WC-2018,Telstar Mechta,Adidas
25,WC-2022,Al Rihla,Adidas
26,WC-2022,Al Hilm,Adidas
27,WC-2026,Trionda,Adidas
28,WC-2026,Trionda Final,Adidas

In [38]:
# delete the first row
match_balls_df = match_balls_df.iloc[1:].reset_index(drop=True)

# add two personalized rows
tiento = {
    'tournament_id': 'WC-1930',
    'ball_name': 'Tiento',
    'manufacturer': np.nan
}
t_model = {
    'tournament_id': 'WC-1930',
    'ball_name': 'T-Model',
    'manufacturer': np.nan
}

match_balls_df = pd.concat([match_balls_df, pd.DataFrame([tiento, t_model])], ignore_index=True)
match_balls_df

,tournament_id,ball_name,manufacturer,ball_id
0,WC-1934,Federale 102,ECAS (Ente Centrale Approvvigionamento Sportiv...,2.0
1,WC-1938,Allen,"Allen, Paris",3.0
2,WC-1950,Duplo T,Superball,4.0
3,WC-1954,Swiss World Champion,"Kost Sport, Basel",5.0
4,WC-1958,Top Star,"Sydsvenska Läder och Remfabriken, Ängelholm (a...",6.0
5,WC-1962,Crack,"Señor Custodio Zamora H., San Miguel, Chile Re...",7.0
6,WC-1966,Challenge 4-Star,Slazenger,8.0
7,WC-1970,Telstar,Adidas,9.0
8,WC-1974,Telstar Durlast,Adidas,10.0
9,WC-1978,Tango,Adidas,11.0
10,WC-1982,Tango España,Adidas,12.0
11,WC-1986,Azteca,Adidas,13.0
12,WC-1990,Etrusco Unico,Adidas,14.0
13,WC-1994,Questra[14],Adidas,15.0
14,WC-1998,Tricolore,Adidas,16.0
15,WC-2002,Fevernova,Adidas,17.0
16,WC-2006,Teamgeist,Adidas,18.0
17,WC-2006,Teamgeist Berlin,Adidas,19.0
18,WC-2010,Jabulani,Adidas,20.0
19,WC-2010,Jo'bulani,Adidas,21.0
20,WC-2014,Brazuca,Adidas,22.0
21,WC-2014,Brazuca Final Rio,Adidas,23.0
22,WC-2018,Telstar 18,Adidas,24.0
23,WC-2018,Telstar Mechta,Adidas,25.0
24,WC-2022,Al Rihla,Adidas,26.0
25,WC-2022,Al Hilm,Adidas,27.0
26,WC-2026,Trionda,Adidas,28.0
27,WC-2026,Trionda Final,Adidas,29.0
28,WC-1930,Tiento,NaN,NaN
29,WC-1930,T-Model,NaN,NaN

In [40]:
# order by tournament_id
match_balls_df = match_balls_df.sort_values(by='tournament_id').reset_index(drop=True)
match_balls_df['ball_id'] = match_balls_df.index + 1
match_balls_df

,tournament_id,ball_name,manufacturer,ball_id
0,WC-1930,T-Model,NaN,1
1,WC-1930,Tiento,NaN,2
2,WC-1934,Federale 102,ECAS (Ente Centrale Approvvigionamento Sportiv...,3
3,WC-1938,Allen,"Allen, Paris",4
4,WC-1950,Duplo T,Superball,5
5,WC-1954,Swiss World Champion,"Kost Sport, Basel",6
6,WC-1958,Top Star,"Sydsvenska Läder och Remfabriken, Ängelholm (a...",7
7,WC-1962,Crack,"Señor Custodio Zamora H., San Miguel, Chile Re...",8
8,WC-1966,Challenge 4-Star,Slazenger,9
9,WC-1970,Telstar,Adidas,10
10,WC-1974,Telstar Durlast,Adidas,11
11,WC-1978,Tango,Adidas,12
12,WC-1982,Tango España,Adidas,13
13,WC-1986,Azteca,Adidas,14
14,WC-1990,Etrusco Unico,Adidas,15
15,WC-1994,Questra[14],Adidas,16
16,WC-1998,Tricolore,Adidas,17
17,WC-2002,Fevernova,Adidas,18
18,WC-2006,Teamgeist Berlin,Adidas,19
19,WC-2006,Teamgeist,Adidas,20
20,WC-2010,Jabulani,Adidas,21
21,WC-2010,Jo'bulani,Adidas,22
22,WC-2014,Brazuca,Adidas,23
23,WC-2014,Brazuca Final Rio,Adidas,24
24,WC-2018,Telstar 18,Adidas,25
25,WC-2018,Telstar Mechta,Adidas,26
26,WC-2022,Al Rihla,Adidas,27
27,WC-2022,Al Hilm,Adidas,28
28,WC-2026,Trionda,Adidas,29
29,WC-2026,Trionda Final,Adidas,30

In [42]:
# edit the 1994 ball name
match_balls_df.loc[match_balls_df['tournament_id'] == 'WC-1994', 'ball_name'] = 'Questra'
# delete everything after the first comma in the manufacturer column for all rows
match_balls_df['manufacturer'] = match_balls_df['manufacturer'].str.split(',').str[0]
match_balls_df

,tournament_id,ball_name,manufacturer,ball_id
0,WC-1930,T-Model,NaN,1
1,WC-1930,Tiento,NaN,2
2,WC-1934,Federale 102,ECAS (Ente Centrale Approvvigionamento Sportivi),3
3,WC-1938,Allen,Allen,4
4,WC-1950,Duplo T,Superball,5
5,WC-1954,Swiss World Champion,Kost Sport,6
6,WC-1958,Top Star,Sydsvenska Läder och Remfabriken,7
7,WC-1962,Crack,Señor Custodio Zamora H.,8
8,WC-1966,Challenge 4-Star,Slazenger,9
9,WC-1970,Telstar,Adidas,10
10,WC-1974,Telstar Durlast,Adidas,11
11,WC-1978,Tango,Adidas,12
12,WC-1982,Tango España,Adidas,13
13,WC-1986,Azteca,Adidas,14
14,WC-1990,Etrusco Unico,Adidas,15
15,WC-1994,Questra,Adidas,16
16,WC-1998,Tricolore,Adidas,17
17,WC-2002,Fevernova,Adidas,18
18,WC-2006,Teamgeist Berlin,Adidas,19
19,WC-2006,Teamgeist,Adidas,20
20,WC-2010,Jabulani,Adidas,21
21,WC-2010,Jo'bulani,Adidas,22
22,WC-2014,Brazuca,Adidas,23
23,WC-2014,Brazuca Final Rio,Adidas,24
24,WC-2018,Telstar 18,Adidas,25
25,WC-2018,Telstar Mechta,Adidas,26
26,WC-2022,Al Rihla,Adidas,27
27,WC-2022,Al Hilm,Adidas,28
28,WC-2026,Trionda,Adidas,29
29,WC-2026,Trionda Final,Adidas,30

In [43]:
match_balls_df.to_csv("data/processed/match_balls.csv", index=False)